# Generated by Django 3.0.5 on 2020-04-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('max_regions', models.IntegerField(default=30)),
                ('max_region_size', models.IntegerField(default=7)),
                ('min_region_size', models.IntegerField(default=3)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='currentRoom',
            new_name='currentArea',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='e_to',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.AddField(
            model_name='room',
            name='exit_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='passable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='start_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adventure.Area'),
            preserve_default=False,
        ),
    ]
