# Generated by Django 3.0.5 on 2020-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200428_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentArea',
            field=models.IntegerField(default=1),
        ),
    ]
