# Generated by Django 3.0.5 on 2020-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200429_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='current_y',
            field=models.IntegerField(default=0),
        ),
    ]
